CREATE TABLE VENDEDOR(
	IDVENDEDOR		UNIQUEIDENTIFIER	NOT NULL,
	NOME			NVARCHAR(150)		NOT NULL,
	EMAIL			NVARCHAR(100)		NOT NULL UNIQUE,
	SENHA			NVARCHAR(40)		NOT NULL,
	DATACRIACAO	DATETIME			NOT NULL,
	PRIMARY KEY(IDVENDEDOR))
GO
