CREATE TABLE [dbo].[VEICULO] (
    [IDVEICULO]    UNIQUEIDENTIFIER NOT NULL,
    [MARCA]        NVARCHAR (150)   NOT NULL,
    [COR]          NVARCHAR (15)    NOT NULL,
    [ANO]          NVARCHAR (15)    NOT NULL,
    [MODELO]       NVARCHAR (150)   NOT NULL,
    [PLACA]        NVARCHAR (20)    NOT NULL,
    [CHASSI]       NVARCHAR (20)    NOT NULL,
    [VALORENTRADA] NVARCHAR (20)    NOT NULL,
    [VALORFINAL]   NVARCHAR (20)    NOT NULL,
    [VALORDEVENDA] NVARCHAR (20)    NOT NULL,
    [MELHORIAS]    NVARCHAR (100)   NOT NULL,
    [IDVENDEDOR]   UNIQUEIDENTIFIER NOT NULL,
    PRIMARY KEY CLUSTERED ([IDVEICULO] ASC),
    FOREIGN KEY ([IDVENDEDOR]) REFERENCES [dbo].[VENDEDOR] ([IDVENDEDOR])
);